<div class="page-size about-view">

    <h2>Island Tours</h2>
    <p>
        Embark on guided island tours that unveil the secrets of Socotra's unique landscapes. Discover hidden gems and breathtaking vistas with our experienced local guides.
    </p>
    <h2>Hotel Reservations
    </h2>
    <p>
        Enjoy a comfortable stay on Socotra with our hassle-free hotel reservation services. Choose from a range of accommodation options that suit your preferences and budget.
    </p>
    <h2>Island Tours</h2>
    <p>
        Embark on guided island tours that unveil the secrets of Socotra's unique landscapes. Discover hidden gems and breathtaking vistas with our experienced local guides.
    </p>
    <h2>Hotel Reservations
    </h2>
    <p>
        Enjoy a comfortable stay on Socotra with our hassle-free hotel reservation services. Choose from a range of accommodation options that suit your preferences and budget.
    </p>
    <div class="icon">
        <a href="facebook.com">
            <img src="/static/media/icons/facebook.svg" />
        </a>
        <a href="twitter.com">
            <img src="/static/media/icons/twitter.svg" />
        </a>
        <a href="instagram.com">
            <img src="/static/media/icons/instagram.png" />
        </a>
    </div>

</div>
<div>
    <?php include_once(ROOT_PATH . "/components/links-view.phtml"); ?>
</div>