<?php
$image_gallery_text_or_login_modal_toggler = 'text';
?>

<div class="top-view" id="top-view">
    <div class="buttons df df-c">
        <button class="slide-button prev-slide" onclick="slideShow(-1)">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
            </svg>
        </button>
        <button class="slide-button next-slide" onclick="slideShow(1)"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
            </svg>
        </button>
    </div>
    <div class="top-view-wrapper df df-c">
        <div class="top-view-slide df df-c fade-in">
            <div class="image">
                <img src="/static/media/image-1.jpg" alt="abc" />
                <div class="top-layer"></div>
            </div>
            <div class="page-size top-view-text df df-dc">
                <h1>Discover Socotra</h1>
                <p>
                    Socotra, often referred to as the "Galapagos of the Indian Ocean," is a UNESCO World Heritage Site known for its rich biodiversity and otherworldly landscapes. From the iconic Dragon's Blood Trees to pristine beaches, Socotra offers a captivating blend of nature and culture.
                </p>
                <a class="btn white-bg black-color" href="/">Explore More</a>
            </div>
        </div>
        <div class="top-view-slide df df-c">
            <div class="image">
                <img src="/static/media/image-5.jpg" alt="abc" />
                <div class="top-layer"></div>
            </div>
            <div class="page-size top-view-text df df-dc">
                <h1>Beyond the Horizon</h1>
                <p>
                    Socotra extends an invitation to explore beyond the horizon, where cerulean waters caress untouched shores. Sink your toes into powdery sands, where time itself seems to slow, and the rhythm of the ocean orchestrates a timeless melody.
                </p>
                <a class="btn white-bg black-color" href="/">Explore More</a>
            </div>
        </div>
        <div class="top-view-slide df df-c">
            <div class="image">
                <img src="/static/media/image-3.jpg" alt="abc" />
                <div class="top-layer"></div>
            </div>
            <div class="page-size top-view-text df df-dc">
                <h1>Cultural Echoes</h1>
                <p>
                    Beyond its natural wonders, Socotra's charm lies in the warmth of its people. Engage with age-old traditions, stories told by the elders, and the vibrant hues of local markets. The cultural heartbeat of Socotra resonates, creating a harmonious blend of tradition and modernity.
                </p>
                <a class="btn white-bg black-color" href="/">Explore More</a>
            </div>
        </div>
    </div>
</div>
<?php
include_once('./components/image-clg.phtml');
?>
<div class="page-size df df-jc text-wrapper">
    <div class='Observe text-wrap'>
        <h1>Your Visitor Experience on Socotra Island</h1>
        <p>
            Welcome to a realm where nature's poetry and cultural echoes intertwine—the immersive visitor experience on Socotra Island. As you step onto this ecological stage, be prepared for a tapestry of moments that will linger in your memory long after the journey concludes.
        </p>
    </div>
    <div class="Observe text-wrap">
        <h1>Morning Hues Over Dixam</h1>
        <p>Awaken to the soft glow of dawn over the Dixam Plateau, where the sun's first rays paint the landscape in hues of amber and gold. The panoramic vistas stretch as far as the eye can see, revealing a world where time appears to stand still.</p>
    </div>
    <div class="Observe text-wrap">
        <h1>Cultural Encounters in Hadibu</h1>
        <p>
            Venture into Hadibu, the island's cultural heart. Navigate bustling markets filled with vibrant fabrics, handcrafted treasures, and the aroma of exotic spices. Engage with locals, and let the tales of their traditions weave a narrative that connects the past with the present.
        </p>
    </div>
    <div class="Observe text-wrap">
        <h1>A Symphony of Flavors</h1>
        <p>
            Savor the culinary delights of Socotra. Whether it's a feast of freshly caught seafood by the shore or a taste of traditional Yemeni cuisine infused with local flavors, each meal is a celebration of the island's rich culinary heritage.
        </p>
    </div>
    <div class="Observe text-wrap">
        <h1>Coastal Retreats and Hidden Coves</h1>
        <p>
            Retreat to secluded coastal havens, where pristine beaches meet the lull of the Arabian Sea. Dive into azure waters, explore hidden coves, and let the gentle waves become your lullaby as you bask in the tranquility of Socotra's untouched shores.
        </p>
    </div>
    <div class="Observe text-wrap">
        <h1>Starry Nights Over Qalansiyah</h1>
        <p>
            As day gives way to night, experience the magic of star-lit skies over Qalansiyah. The absence of city lights unveils a celestial masterpiece, inviting you to contemplate the universe from a vantage point untouched by urban glare. </p>
    </div>
</div>
<div class='page-size bio'>
    <h1 class="title-2x ckk3">Most Beautiful Places on Socotra Island</h1>
</div>
<div class='page-size places'>
    <section>
        <div>
            <img class="lazy-load" data-src="/static/media/places/red-dragon.jpg" alt="places" />
            <h2>Dixam Plateau A Highland Haven Above the Clouds</h2>
        </div>
        <div class='text'>
            <p>
                Perched atop the heights of Socotra, the Dixam Plateau stands as a testament to the island's breathtaking beauty. Crowned by ancient Dragon's Blood Trees, this highland sanctuary offers visitors a panoramic escape into a realm where the air is crisp, and the views stretch endlessly.
            </p>
        </div>
    </section>
    <section>
        <div>
            <img class="lazy-load" data-src="/static/media/places/beach.jpg" alt="places" />
            <h2>Qalansiyah Beach Turquoise Tranquility</h2>
        </div>
        <div class='text'>
            <p>
                Step onto the shores of Qalansiyah Beach, where the soft white sand meets the azure embrace of the Arabian Sea. With its crystal-clear waters and a backdrop of dramatic cliffs, this coastal paradise invites you to unwind in the lap of natural beauty. Explore the underwater wonders or simply bask in the serenity of one of Socotra's most picturesque gems.

            </p>
        </div>
    </section>
    <section>
        <div>
            <img class="lazy-load" data-src="/static/media/places/forest.jpg" alt="places" />
            <h2>Firmhin Forest Mystical Canopy of Socotra
            </h2>
        </div>
        <div class='text'>
            <p>
                Enter the enchanting embrace of Firmhin Forest, a verdant sanctuary where the air is scented with the fragrance of ancient flora. Venture beneath the dense canopy of endemic Socotran trees, including the iconic Dragon's Blood Trees, as they weave a tapestry of greenery against the Socotran sky. Discover the magic of this lush forest, where time feels suspended, and every step reveals the secrets of Socotra's unique and ancient ecosystems.
            </p>
        </div>
    </section>
    <section>
        <div>
            <img class="lazy-load" data-src="/static/media/places/lagoon.jpg" alt="places" />
            <h2>Detwah Lagoon Where Cliffs Kiss Tranquil Waters
            </h2>
        </div>
        <div class='text'>
            <p>
                Nestled along the coastline of Socotra, Detwah Lagoon unveils a mesmerizing blend of nature's artistry. Turquoise waters gently cradle the shore, framed by dramatic cliffs that stand as sentinels to the serene beauty below. Lose yourself in the tranquility of this breathtaking lagoon, where every moment reflects the harmony between land and sea, making Detwah a coastal jewel on the crown of Socotra.
            </p>
        </div>
    </section>
    <section>
        <div>
            <img class="lazy-load" data-src="/static/media/places/aomak.jpg" alt="places" />
            <h2>Aomak Beach A Secluded Shoreline Retreat
            </h2>
        </div>
        <div class='text'>
            <p>Aomak Beach beckons with its secluded charm, offering a pristine escape along the shores of Socotra. This hidden gem boasts unique rock formations that guard a stretch of soft, white sand and the clear, inviting waters of the Arabian Sea. Whether you seek solitude or a quiet communion with nature, Aomak Beach unfolds as a tranquil canvas where the beauty of Socotra meets the gentle lull of the ocean, creating an idyllic coastal haven.

            </p>
        </div>
    </section>
    <section>
        <div>
            <img class="lazy-load" data-src="/static/media/places/peak.jpg" alt="places" />
            <h2>Skand Peak At the Pinnacle of Socotra's Majesty
            </h2>
        </div>
        <div class='text'>
            <p>Rising majestically as the highest point on Socotra, Skand Peak offers a breathtaking vantage point for those seeking awe-inspiring views. Perched at the island's summit, this lofty peak provides a panoramic spectacle, revealing the diverse landscapes that define Socotra. As the cool mountain air embraces you, absorb the beauty that unfolds in every direction, making Skand Peak an unparalleled destination for those who aspire to touch the sky in the heart of this natural wonderland.
            </p>
        </div>
    </section>
    <section>
        <div>
            <img class="lazy-load" data-src="/static/media/places/cave.jpg" alt="places" />
            <h2>Hoq Cave A Glimpse into Socotra's Subterranean Wonders
            </h2>
        </div>
        <div class='text'>
            <p>Hidden beneath the surface of Socotra's ancient landscapes, Hoq Cave unveils a mesmerizing world of underground enchantment. Venture into the depths, where stalactites and stalagmites intertwine, creating a subterranean masterpiece that echoes the island's rich geological history. Hoq Cave invites intrepid explorers to discover the secrets hidden in its rocky embrace, offering a unique journey into the heart of Socotra's geological wonders.</p>
        </div>
    </section>
    <section>
        <div>
            <img class="lazy-load" data-src="/static/media/places/homhil.jpg" alt="places" />
            <h2>Homhil Plateau Terraced Tranquility Above the Clouds
            </h2>
        </div>
        <div class='text'>
            <p>
                Perched like a tranquil oasis atop Socotra's rugged terrain, Homhil Plateau unfolds as a highland haven. Dotted with terraced fields and traditional Socotran villages, this elevated sanctuary offers panoramic views of the island's diverse landscapes. Embrace the serenity of Homhil, where time seems to stand still, and the harmony between ancient traditions and untouched nature paints a captivating portrait of Socotra's timeless allure.
            </p>
        </div>
    </section>
</div>
<div class="page-size bio">
    <h1 class="title-2x ckk3">Socotra Island Weather</h1>
    <br />
</div>
<div class="page-size weather">
    <div class="inner-weather">
        <div class="weather-top-view" id="weather-page">
            <div class="temp">
                <h3>29</h3>
                <span>°C</span>
            </div>
            <div class="text">
                <div>
                    <img src="" alt="" id="page-weather-image">
                </div>
                <span class="xqew">
                    <span class="cond"></span>
                    Wind speed <span class="wind"></span> KM/H <span class="hum"></span>% Humidity.
                </span>
            </div>
            <h2 class="xkk"></h2>
            <div id="hourly"></div>
            <div id="days">
            </div>
        </div>
    </div>
</div>
<div class='page-size bio'>
    <h1 class="title-2x ckk3">Socotra Island on map</h1>
</div>
<div class="page-size map places">
    <iframe class='socotra-map' src="https://www.google.com/maps/d/embed?mid=19D8gM3Qw7pevd1aNjCiZ40v5LWQ&hl=en_US&ehbc=2E312F" width="640" height="480"></iframe>
</div>
<div>
    <?php include_once(ROOT_PATH . "/components/links-view.phtml"); ?>
</div>
<script src="/static/js/image-slide.js"></script>