<div class="page-size logout-view">
    <div class="form-modal">
        <div class="in-modal">
            <div class="form">
                <form autocomplete="on" id='sign-in-form'>
                    <h2>USER LOGOUT</h2>
                    <p>
                        Please be notified if you logout from socotra.co you can miss most important updates and notification about socotra. so if you want to get notification and updates then keep login.
                    </p>
                    <div class="flex" style="flex-direction: column;">
                        <button type="button" class="login-btn btn" onclick="signOut()">Sign Out</button>
                        <span id="alert-text"></span>
                    </div>
                    <p class="lower-message">try another account? then please <a href='/?p=login'>sign in.</a></p>
                </form>
            </div>
        </div>
    </div>
</div>