<div class="weather-view">
    <div class="top-view" id="top-view">

        <div class="top-view-wrapper df df-c">
            <div class="top-view-slide df df-c fade-in">
                <div class="image">
                    <img src="/static/media/image-1.jpg" alt="abc" />
                </div>

            </div>
            <div class="top-view-slide df df-c">
                <div class="image">
                    <img src="/static/media/image-5.jpg" alt="abc" />
                </div>

            </div>
            <div class="top-view-slide df df-c">
                <div class="image">
                    <img src="/static/media/image-3.jpg" alt="abc" />
                </div>

            </div>
        </div>
    </div>

    <div class="page-size weather">
        <div class="inner-weather">
            <div class="weather-top-view" id="weather-page">
                <div class="temp">
                    <h3>29</h3>
                    <span>°C</span>
                </div>
                <div class="text">
                    <div>
                        <img src="" alt="" id="page-weather-image">
                    </div>
                    <span class="xqew">
                        <span class="cond"></span>
                        Wind speed <span class="wind"></span> KM/H <span class="hum"></span>% Humidity.
                    </span>
                </div>
                <h2 class="xkk"></h2>
                <div id="hourly"></div>
                <div id="days">
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/static/js/image-slide.js"></script>