<div class="page-size weather">
    <div class="inner-weather">
        <div class="weather-top-view" id="weather-page">
            <div class="temp">
                <h3>29</h3>
                <span>°C</span>
            </div>
            <div class="text">
                <div>
                    <img src="" alt="" id="page-weather-image">
                </div>
                <span class="xqew">
                    <span class="cond"></span>
                    Wind speed <span class="wind"></span> KM/H <span class="hum"></span>% Humidity.
                </span>
            </div>
            <h2 class="xkk"></h2>
            <div id="hourly"></div>
            <div id="days">
            </div>
        </div>
    </div>