<?php

?>
<header class="fade-in" id="header">
	<nav class="page-size df-ac">
		<ul class="ck">
			<a href="/" class="logo">
				<img src="/static/media/logo-light.png" alt="socotra.co" />
			</a>
		</ul>
		<ul class="ytill df df-c">
			<li class="last-li">
				<a href="/admin.php?p=<?php if ($user) echo 'logout';
										else  echo 'login'; ?>" style="display: flex;justify-content:center;align-items:center;">

					<span style="text-transform: uppercase;margin-right:8px"><?php echo $user ? $user : "Login"; ?></span>
					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
						<path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
					</svg>
				</a>
			</li>

		</ul>
	</nav>
</header>