<div class="page-size logout-view" style="margin-top: 10px">
    <div class="form-modal">
        <div class="in-modal">
            <div class="form">
                <form action="/admin.php?p=logout">
                    <h2>ADMIN LOGOUT</h2>
                    <p>
                        logout from your account this is best practice if you loggin out from your account after managing website.
                    </p>
                    <input type="hidden" name="admin-logout" value="1">
                    <div class="flex" style="flex-direction: column;">
                        <button type="button" onclick="window.location.href=window.location.href + '&admin-logout=1'" class="login-btn btn">Sign Out</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>