<div class="wrapper">
    <h2>MANAGE VISA'S</h2>
    <p>You can remove visa. please keep in mind any action is not reversable so take any action carefully.</p>
    <table class="admin-table-view">
        <thead>
            <tr>
                <th>#</th>
                <th>ID</th>
                <th>NAME</th>
                <th>NATIONALITY</th>
                <th>PASSPORT NO</th>
                <th>ADDRESS</th>
                <th>CREATED AT</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($visas as $visa) { ?>
                <tr>
                    <td><?php echo ++$i; ?></td>
                    <td><?php echo $visa["id"]; ?></td>
                    <td><?php echo $visa["name"]; ?></td>
                    <td><?php echo $visa["nationality"]; ?></td>
                    <td><?php echo $visa["passport_no"]; ?></td>
                    <td><?php echo $visa["permanent_addr"]; ?></td>
                    <td><?php echo date('M d Y', strtotime($visa["createdAt"])); ?></td>
                    <td>
                        <button class="btn white-bg black-color delete-btn" onclick="deleteItem(<?php echo $visa['id']; ?>, 'visa')">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                            </svg>
                        </button>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>