<div class="page-size link-view" style="margin:auto;">
    <h1>Explore Socotra</h1>
    <div class="link-wrap">
        <a href="/?p=biodiversity" title="click to visit biodiversity">
            <img src="/static/media/bio1.webp" />
            <h3>Biodiversity</h3>
            <p>
                Embark on a journey to Socotra, a biodiversity hotspot! Known for its unique flora and fauna, Socotra boasts the iconic Dragon Blood Trees, diverse marine life, and endemic species. Explore nature's wonders in this ecological haven.
            </p>
        </a>
        <a href="/?p=get-visa" title="click to visit get visa page">
            <img src="/static/media/visa-application.jpg" />
            <h3>Visa Assistance</h3>
            <p>
                Planning a trip to Socotra? Make your travel hassle-free with our visa assistance. Simply fill out our user-friendly visa form on the "Get Visa" page, and let us guide you through the process. Ensure a smooth and enjoyable experience as you prepare for your Socotra adventure!
            </p>
        </a>
         <a href="/?p=hotel-reservation" title="click to visit Hotel reservation">
            <img src="/static/media/hotel-res-2.jpg" />
            <h3>Hotel Reservation</h3>
            <p>
            Experience the ease of booking your stay on Socotra through our website. Whether it's the serene Heathrow Hotel nestled by the iconic Dragon Blood Trees or the charming Summerland Hotel, we've got your accommodation needs covered. Simply use our Hotel Reservation form, choose your preferred dates, and embark on a journey where comfort meets tranquility. Your Socotra getaway starts with a click!
            </p>
        </a>
        <a href="/?p=weather" title="click to visit weather page">
            <img src="/static/media/weather.webp" />
            <h3>Weather of socotra</h3>
            <p>
                Stay informed about Socotra's weather effortlessly with our dedicated Weather page. Explore current conditions, temperature trends, and hourly forecasts. Whether you're planning outdoor adventures or just curious about the island's climate, our user-friendly interface provides real-time data. From sunny days to the occasional drizzle, Socotra's weather is just a click away. Explore, plan, and embrace the island experience with confidence!
            </p>
        </a>
    </div>
</div>