<div class="form-modal">
    <div class="in-modal">
        <div class="form">
            <form autocomplete="on">
                <h2>USER LOGIN</h2>
                <p>
                    Resume your Socotra experience here. If you're planning a new adventure or revisiting great memories, use our login. Just type in your email address and password below to continue exploring.
                </p>
                <div class="flex-yxz">
                    <div class="a03x full-w">
                        <label for="username">Enter your email address</label>
                        <input type="text" id="username" name="username" placeholder="username or email address." />
                    </div>
                </div>
                <div class="flex-yxz">
                    <div class="a03x full-w">
                        <label for="password">Enter your password</label>
                        <input type="password" name="password" id="password" placeholder="Enter password" />
                    </div>
                </div>
                <div>
                </div>
                <div class="flex" style="flex-direction: column;">
                    <input type="submit" class="login-btn" value="Sign In" />
                    <!-- <span class="message danger">Account successfully created!</span> -->
                </div>
                <p class="lower-message">Don't have an account yet? please <a href='/signup'>sign up.</a></p>

            </form>
        </div>
    </div>
</div>